---
name: Mopidy Percy
version: dev46
slug: mopidy_percy
panel_icon: mdi:music-circle
description: Mopidy is an extensible music server
url: https://github.com/Gurutasker/addon-mopidy-lounge-prod
ingress: true
ingress_entry: iris/
ingress_stream: true
arch:
  - amd64
auth_api: true
audio: true
ports:
  6600/tcp: 6601
  5555/udp: 5556
  4478/tcp: 6660
ports_description:
  6600/tcp: Mopidy
  5555/udp: Autoaudiosink
  80/tcp: Web interface (Not required for Ingress)
map:
  - config
  - share:rw
  - ssl
  - media:rw
options:
  system_packages: []
  python_packages: []
  settings: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  system_packages:
    - str
  python_packages:
    - str
  settings:
    - name: str
      value: str
  leave_front_door_open: bool?
